### PR TITLE
Adding BH3

### PR DESCRIPTION
**Pull request by mkenne15**
Adding GAIA BH3. Will update the bibcode once it's been published

### CODE REVIEW

**Comment by kareemelbadry** [comment]
Sweet! Are you sure about the K2 value? From the RV plot, it looks smaller to me.

**Comment by mkenne15** [comment]
Yeah, spot on that I made an error - in my haste I just grabbed gamma from the paper. I'll fix this in the morning.

**Comment by mkenne15** [comment]
@kareemelbadry I've removed K2 as they don't actually give it anywhere in the paper. I've emailed Pasquale for it, and will update in the mean time. Let me know if happy to approve now.

**Comment by kareemelbadry** [comment]
@mkenne15  We could predict it based on m1, m2, P, and ecc. From the parameters of the combined solution and reported uncertainties, I get K2 = 56.6 +/- 0.8. The true uncertainty might be a bit less because parameters are correlated with one another, but that seems like a reasonable guess to me.

**Comment by mkenne15** [comment]
Very close - Pasquale just emailed me saying it was 56.61+/-0.49 km/s. Updated the pull request to reflect this now.

**Review by kareemelbadry — COMMENTED** [review]
looks good!

**Review by kareemelbadry — APPROVED** [review]
looks good!

**Pull request merged**
